use bcder::{ConstOid, Oid};

pub struct OidInfo {
    pub asn1_object_identifier: &'static str,
    pub dot_name: &'static str,
    pub bytes: ConstOid,
}

// See RFC 8017: PKCS #1: RSA Cryptography Specifications Version 2.2
// https://www.rfc-editor.org/info/rfc8017/#appendix-A.1
// https://www.rfc-editor.org/info/rfc8017/#appendix-C
pub const RSA_OID: OidInfo = OidInfo {
    asn1_object_identifier: "rsaEncryption",
    dot_name: "1.2.840.113549.1.1.1",
    bytes: Oid(&[42, 134, 72, 134, 247, 13, 1, 1, 1]), // Generated by bcder crate binary mkoid
};

// See RFC 5480: Elliptic Curve Cryptography Subject Public Key Information
// https://www.rfc-editor.org/info/rfc5480/#section-2.1.1
pub const EC_OID: OidInfo = OidInfo {
    asn1_object_identifier: "id-ecPublicKey",
    dot_name: "1.2.840.10045.2.1",
    bytes: Oid(&[42, 134, 72, 206, 61, 2, 1]), // Generated by bcder crate binary mkoid
};

// See RFC 5480: Elliptic Curve Cryptography Subject Public Key Information
// https://www.rfc-editor.org/info/rfc5480/#section-2.1.1.1
pub const SECP256R1_OID: OidInfo = OidInfo {
    asn1_object_identifier: "secp256r1",
    dot_name: "1.2.840.10045.3.1.7",
    bytes: Oid(&[42, 134, 72, 206, 61, 3, 1, 7]),
};

// See RFC 5480: Elliptic Curve Cryptography Subject Public Key Information
// https://www.rfc-editor.org/info/rfc5480/#section-2.1.1.1
pub const SECP384R1_OID: OidInfo = OidInfo {
    asn1_object_identifier: "secp384r1",
    dot_name: "1.3.132.0.34",
    bytes: Oid(&[43, 129, 4, 0, 34]),
};

// // See RFC 8410: Algorithm Identifiers for Ed25519, Ed448, X25519, and X448 for Use in the Internet X.509 Public Key Infrastructure
// // https://www.rfc-editor.org/info/rfc8410/#section-3
// const ED25519_OID: OidInfo = OidInfo {
//     asn1_object_identifier: "id-Ed25519",
//     dot_name: "1.3.101.112",
//     bytes: Oid(&[43, 101, 112]),
// };
